### test deployed app
POST https://fso-part-3-qt29.onrender.com/api/contacts
content-type: application/json

{
    "name": "AddedOnDeployedAppUsingRESTClient",
    "number": "099"
}

### test local host
POST http://localhost:3001/api/contacts
content-type: application/json

{
    "name": "Testing locally using RESTClient",
    "number": "011"
}